[package]
name = "if-watch-github"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
if-watch = { git = "https://github.com/mxinden/if-watch.git" }
